### ISSUE TITLE
robosense helios 5515 csv in main required

### ISSUE THREAD

**Issue by chivas1000** [tier4/nebula#115]
Hi developers,
I want to use your nebula driver to start my robosense helios lidar, and I want to open the "nebula/nebula_ros/launch/robosense_launch.all_hw.xml" file

but finding that it lacks
`<arg name="calibration_file" default="$(find-pkg-share nebula_decoders)/calibration/robosense/Helios5515.csv"/>`
which I did not see it in nebula main branch.

Is it avaliable for this csv file? and I want to use it as a reference to modify as my own helios.csv which I am using helios 32(fov 31 degrees: https://www.robosense.ai/en/rslidar/RS-Helios)

Any assistance would be appreciated, thanks

**Comment by mebasoglu** [comment]
Hello @chivas1000 , currently calibration files aren't required for Robosense in Nebula. I forgot to delete that line from launch file. You can remove that line.
