### ISSUE TITLE
Hesai unit test pointclouds contain duplicate points

### ISSUE THREAD

**Issue by mojomex** [tier4/nebula#48]
## Description

The reference `.pcl` files in the Hesai unit tests contain large numbers of identical points, often close to half of the total points in the scan:

| Sensor model | Total # points | duplicate # points | % duplicate |
|-|-:|-:|-:|
| 40P | 108663 | 51941 | 47.8 |
| 64 | 179121 | 85501 | 47.7 |
| AT128 | 10205 | 0 | 0.0 |
| QT64 | 64452 | 30743 | 47.7 |
| XT32 | 121648 | 58627 | 48.2 |
| XT32M | 13404 | 0 | 0.0 |

Unit tests are passing only because the `dual_return_distance_threshold` parameter is set to `0.0`. This is also the case in `nebula_launch.py` but is set to a default value of `0.1` in `hesai_launch_all_hw.xml`.

## Expected behavior

There are no duplicate points in the reference data of unit tests, and decoders should be tested (**and launched!**) with a `dual_return_distance_threshold > 0` or identical point checks (such as AT128 has).

Reasoning: Duplicated points provide no value but take up memory, thus increasing DDS latency, processing resources etc.

## Actual behavior

There are duplicate points in the reference data, and while decoders have code to filter by `dual_return_distance_threshold`, this parameter is never set in the current `nebula_launch.py`, thus implicitly being initialized to `0` and making the filter code do nothing. In the unit tests, it is explicitly set to `0`.

## Steps to reproduce

1. In all `hesai_ros_decoder_test_<model>.cpp` unit test files, replace the `void checkPCDs(nebula::drivers::NebulaPointCloudPtr, pcl::PointCloud<pcl::PointXYZ>::Ptr)` function by the following:
```c++
void checkPCDs(nebula::drivers::NebulaPointCloudPtr pc, pcl::PointCloud<pcl::PointXYZ>::Ptr ref_pc)
{
  /*
   * Check for duplicate points in reference pointcloud
   */

  size_t n_neighbor_duplicates = 0;
  for (size_t i = 1; i < ref_pc->size(); ++i) {
    auto & p1 = ref_pc->points[i - 1];
    auto & p2 = ref_pc->points[i];
    if (p1.x == p2.x && p1.y == p2.y && p1.z == p2.z) {
      n_neighbor_duplicates++;
    }
  }

  std::cout << "ref_pcl n_duplicates: " << n_neighbor_duplicates << std::endl;
  std::cout << "ref_pcl n_total:      " << ref_pc->points.size() << std::endl;

  /*
   * Do the actual unit tests
   */

  EXPECT_EQ(pc->points.size(), ref_pc->points.size());
  for (uint32_t i = 0; i < pc->points.size(); i++) {
    auto p1 = pc->points[i];
    auto p2 = ref_pc->points[i];

    EXPECT_FLOAT_EQ(p1.x, p2.x);
    EXPECT_FLOAT_EQ(p1.y, p2.y);
    EXPECT_FLOAT_EQ(p1.z, p2.z);
  }
}
```

2. Build and run the unit tests
3. Observe the output:
```shell
ref_pcl n_duplicates: 58627
ref_pcl n_total:      121648
```

**Comment by drwnz** [comment]
@amc-nu I think we need to change the default settings of `dual_return_distance_threshold` and re-generate the unit test data to match.
